engines:
  radon:
    enabled: true
    config:
      python_version: 3
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
          mass_threshold: 32
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
      - TODO
      - NTS
      - NOTE
      - HACK
ratings:
   paths:
   - "**.py"
exclude_paths:
- "verto/tests/*"
