language: python

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

# Install dependencies
install:
  - pip install flake8
  - pip install .
  - pip install -r requirements-dev.txt

# Runs test suite
script:
  - flake8
  - coverage run --rcfile=.coveragerc -m verto.tests.start_tests --travis
after_success:
  - coverage xml -i
  - coverage report -m --skip-covered
  - bash <(curl -s https://codecov.io/bash)

# Stop email notifications but post to organisation Slack channel
notifications:
  email: false
  slack:
    rooms: deptfunstuff:abJKvzApk5SKtcEyAgtswXAv
    on_success: change
    on_failure: change

addons:
    code_climate:
        repo_token: e8d3f32c2549e7919e154bc5506d4cc743a03408f3ca2bf957020c3e5f826eaf
